### ISSUE TITLE
Respuesta a newGateway

### ISSUE THREAD

**Issue by toniadame** [jose908/entomatic-server#21]
La respuesta a newGateway funciona bien :)
Eso sí, la hora que me envias no está actualizada. Entiendo que has copiado por defecto el valor "20150513180453".

---

WiFi switched ON
Joined
MENSAJE HTTP: idgw=0013A200408BCD4B&lat=44.3252&lon=6.1152

HTTP query OK.
WIFI.answer:HTTP/1.1 200 OK
X-Powered-By: Sails <sailsjs.org>
Access-Control-Allow-Origin: 
Access-Control-Allow-Credentials: 
Access-Control-Allow-Methods: 
Access-Control-Allow-Headers: 
Content-Type: text/html; charset=utf-8
Content-Length: 40
ETag: W/"28-3504850704"
set-cookie: sails.sid=s%3AKLDwjjLGoTjvuylC1Uy2VVBxCYiWJHPP.zHRvAetoGzQB%2FbeAAD8pl6c1Sg2ycLI8mek6mfuLnwI; Path=/; HttpOnly
Date: Thu, 14 May 2015 10:18:59 GMT
Connection: close

0|20150513180453|0013A200408BCD4B|_CLOS__CLOS_

---

**Comment by jose908** [comment]
No la envía actualizada porque esa MAC ya está dada de alta (aproveché la url de ejemplo que me pasaste), entonces envía la fecha de inserción original (ayer cuando probé). Si fuese una gateway nueva, sí enviaría la fecha de inserción (create_date).

**Comment by toniadame** [comment]
WoW! Genial! :)

Probaré entonces con MACs nuevas :)
