### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by gabrielmd** [jose908/entomatic-server#6]
Place: Home
Missing real time chart.

**Comment by gabrielmd** [comment]
Still missing, but we may skip this.

**Comment by jose908** [comment]
Any ideas of anything interesting (chart) to show as a report?

**Comment by gabrielmd** [comment]
One option is to show one chart for each measurement type.
Each chart would show the measurements from the past 24 hours from all the nodes (one color each).

It may become a mess for a high number of nodes, but it is an option.

**Comment by gabrielmd** [comment]
Or you can show the number of measurements taken in the last 24 hours per measurement type.

Just count and show the bars (in our case, 5).
